apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose convert -f docker-compose.yml","kompose.version":"1.20.0 (f3d54d784)"},"labels":{"io.kompose.service":"back"},"name":"back","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.network/myapp":"true","io.kompose.service":"back"}},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose convert -f docker-compose.yml","kompose.version":"1.20.0 (f3d54d784)"},"labels":{"io.kompose.network/myapp":"true","io.kompose.service":"back"}},"spec":{"containers":[{"image":"radzhiv/back:v1","name":"api","ports":[{"containerPort":3000}]}]}}}}
  creationTimestamp: "2021-07-19T17:22:26Z"
  generation: 1
  labels:
    io.kompose.service: back
  name: back
  namespace: default
  resourceVersion: "1536423"
  selfLink: /apis/apps/v1/namespaces/default/deployments/back
  uid: 67990114-a1a5-47fe-bd65-0baccdf8b11b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.network/myapp: "true"
      io.kompose.service: back
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: back
    spec:
      containers:
      - image: radzhiv/back:v1
        imagePullPolicy: IfNotPresent
        name: api
        envFrom:
        - secretRef:
           name: env-back
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-07-19T17:22:28Z"
    lastUpdateTime: "2021-07-19T17:22:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-19T17:22:26Z"
    lastUpdateTime: "2021-07-19T17:22:28Z"
    message: ReplicaSet "back-6cb477c96b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
