apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  labels:
    io.kompose.service: data-script
  name: data-script
spec:
  replicas: 1
  selector:
     matchLabels:
      io.kompose.network/myapp: "true"
      io.kompose.service: data-script
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data-script
    spec:
      initContainers:
      - image: radzhiv/data-script:v1
        name: my-init-container
        envFrom:
        - secretRef:
            name: data-script
        command: ['sh', '-c', "until mysql -h ${MYSQL_DB_HOST} -u ${MYSQL_USER} -p${MYSQL_USER_PASSWORD} -e 'show databases;'; do echo waiting for mydb; sleep 2; done"]
      containers:
      - image: radzhiv/data-script:v1
        name: data-script
        envFrom:
        - secretRef:
            name: data-script
       