apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: "2021-07-19T17:49:02Z"
  labels:
    io.kompose.service: front
  name: front
  namespace: default
  resourceVersion: "1541864"
  selfLink: /api/v1/namespaces/default/services/front
  uid: 480dc7d5-a24a-4eca-9809-61b91bd3c871
spec:
  clusterIP: 10.106.252.203
  externalTrafficPolicy: Cluster
  ports:
  - name: "3001"
    nodePort: 30001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    io.kompose.service: front
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
